package com.github.uryyyyyyy.javaSamples.javaIO;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shiba' at '12/21/15 12:35 PM' with Gradle 2.9
 *
 * @author shiba, @date 12/21/15 12:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
